#!/usr/bin/awk -f
BEGIN {
    a["A X"] = 1 + 3
    a["A Y"] = 2 + 6
    a["A Z"] = 3 + 0

    a["B X"] = 1 + 0
    a["B Y"] = 2 + 3
    a["B Z"] = 3 + 6

    a["C X"] = 1 + 6
    a["C Y"] = 2 + 0
    a["C Z"] = 3 + 3

    b["A X"] = 3 + 0
    b["A Y"] = 1 + 3
    b["A Z"] = 2 + 6

    b["B X"] = 1 + 0
    b["B Y"] = 2 + 3
    b["B Z"] = 3 + 6

    b["C X"] = 2 + 0
    b["C Y"] = 3 + 3
    b["C Z"] = 1 + 6
}
{
    sum_a += a[$0]
    sum_b += b[$0]
}
END {
    print sum_a
    print sum_b
}