#!/usr/bin/awk -f
BEGIN {
    FS="[,-]"
}
{
    if($1 == $3){
        cover +=1
        include +=1;
    } else if($2 == $4) {
        cover +=1
        include +=1
    } else if($2 < $3) {
        0
    } else if($4 < $1) {
        0;
    } else if($1 > $3) {
        if($2 < $4){
            cover+=1
            include+=1;
        } else {
            include+=1; 
        }
    } else { # $1 < $3
        if($2 < $4){
            include+=1;
        } else {
            cover+=1;
            include+=1;
        }
    }
}
END {
    print cover
    print include
}