#!/usr/bin/awk -f
BEGIN { FS="[,-]" }
{
    if($1 == $3 || $2 == $4) {
        cover +=1
        include +=1
    } else if($2 < $3 || $4 < $1) {
        0
    } else {
        include+=1
        if($2 < $4 && $1 > $3) {
            cover+=1
        } else if($2 > $4 && $1 < $3) {
            cover+=1
        }
    }
}
END {
    print "{\"part_one\":" cover ",\"part_two\":" include "}"
}